name: bozorlik
description: "A new Flutter project."

publish_to: 'none'

version: 1.0.0+3

environment:
  sdk: ">=3.7.0 <4.0.0"

dependencies:
  flutter:
    sdk: flutter

  json_annotation: ^4.9.0
  freezed_annotation: ^3.1.0
  flutter_hooks: ^0.20.5
  hooks_riverpod: ^2.6.1
  riverpod_annotation: ^2.6.1

  cupertino_icons: ^1.0.8
  go_router: ^16.1.0
  equatable: ^2.0.7
  dio: ^5.9.0
  logger: ^2.6.1
  jwt_decoder: ^2.0.1
  flutter_svg: ^2.2.0
  shared_preferences: ^2.5.3
  cached_network_image: ^3.4.1
  shimmer: ^3.0.0
  carousel_slider: ^5.1.1
  easy_localization: ^3.0.8
  mask_text_input_formatter: ^2.9.0
  dropdown_button2: ^2.3.9
  infinite_scroll_pagination: ^4.1.0
  package_info_plus: ^8.3.1
  icons_launcher: ^3.0.2
  pdf: ^3.11.3
  open_filex: ^4.7.0
  toastification: ^3.0.3


dev_dependencies:
  flutter_test:
    sdk: flutter

  build_runner: ^2.4.6
  riverpod_lint: ^2.6.5
  riverpod_generator: ^2.4.0
  flutter_lints: ^5.0.0
  freezed: ^3.1.0
  json_serializable: ^6.9.5



flutter:


  uses-material-design: true

  assets:
    - assets/svg/
    - assets/png/
    - assets/translations/
    - assets/fonts/

icons_launcher:
  image_path: "assets/png/logo.png"
  platforms:
    android:
      enable: true
    ios:
      enable: true