// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDhJE4MD_satLcyRSbgtBvI8IjREUkVcvA',
    appId: '1:789077363083:web:9d593a1dd9a032c091078e',
    messagingSenderId: '789077363083',
    projectId: 'bozorapp-151f6',
    authDomain: 'bozorapp-151f6.firebaseapp.com',
    storageBucket: 'bozorapp-151f6.firebasestorage.app',
    measurementId: 'G-0Q8FQXLPHD',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBjKi0ohxmNsuHT2PAZjhkaCm6w-9Xofc4',
    appId: '1:789077363083:android:02b2537ebc4317cc91078e',
    messagingSenderId: '789077363083',
    projectId: 'bozorapp-151f6',
    storageBucket: 'bozorapp-151f6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCKzbA2Axmq3cnYo1gOyzXxxCu5NGP4XDg',
    appId: '1:789077363083:ios:fbcd2478657c7a1591078e',
    messagingSenderId: '789077363083',
    projectId: 'bozorapp-151f6',
    storageBucket: 'bozorapp-151f6.firebasestorage.app',
    iosBundleId: 'uz.bozorlik.app',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCKzbA2Axmq3cnYo1gOyzXxxCu5NGP4XDg',
    appId: '1:789077363083:ios:fbcd2478657c7a1591078e',
    messagingSenderId: '789077363083',
    projectId: 'bozorapp-151f6',
    storageBucket: 'bozorapp-151f6.firebasestorage.app',
    iosBundleId: 'uz.bozorlik.app',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDhJE4MD_satLcyRSbgtBvI8IjREUkVcvA',
    appId: '1:789077363083:web:30331079ec6e26e091078e',
    messagingSenderId: '789077363083',
    projectId: 'bozorapp-151f6',
    authDomain: 'bozorapp-151f6.firebaseapp.com',
    storageBucket: 'bozorapp-151f6.firebasestorage.app',
    measurementId: 'G-Y5PTTDHD36',
  );
}
